### ISSUE TITLE
[API]Implement and provide sign up and login API

### ISSUE THREAD

**Issue by ParkJong-Hun** [ParkJong-Hun/Linkument#24]
## Summary
Implement an API that allows mobile apps to interact with an external DB.

### Todo
- [x] Implement the Login controller
- [x] Implement the Login repository
- [x] Implement the Login service
- [x] Implement error handler around the Login function
- [ ] Implement encryption
- [ ] Implement test around the Login

### Goal
Stable login API can be provided
