### ISSUE TITLE
[API] Normalize the API

### ISSUE THREAD

**Issue by ParkJong-Hun** [ParkJong-Hun/Linkument#60]
## Summary
Since the development proceeded without any confirmation at the moment, it is expected that there will be quite a few errors.  
Modify all APIs and code of Android apps to make it the intended movement.

### Todo
- [x] test login api
  - [x] check request, response of login api, db
- [x] test token api
  - [x] check request, response of token api
  - [ ] write token api test file

### Goal
Error does not exist.

**Comment by ParkJong-Hun** [comment]
The work hasn't been completed yet will be written after studying more about the test.
